env:
  global:
  - GIT_COMMITTER_NAME=y-kurami
  - GIT_COMMITTER_EMAIL=yosuke.kurami@gmail.com
  - GIT_AUTHOR_NAME=Quramy
  - GIT_AUTHOR_EMAIL=yosuke.kurami@gmail.com
  - HIDE_VIM=1
language: node_js
node_js:
- '11'
before_install:
- 'pushd test/ && yarn install && popd'
script:
- bash runtest-all-ts.sh
cache:
  yarn: true
